import StyleDictionary from 'style-dictionary';

// Custom format for TypeScript generation with proper token resolution
StyleDictionary.registerFormat({
  name: 'typescript/tokens',
  format: function(dictionary) {
    // Build color system from resolved tokens
    const colorSystem = {};
    const spacingScale = {};
    const shadowScale = {};
    
    // Process all resolved tokens
    dictionary.allTokens.forEach(token => {
      if (token.type === 'color' && token.path[0] === 'color') {
        // Handle semantic colors that reference primitive colors
        const [, colorName, shade] = token.path;
        if (!colorSystem[colorName]) {
          colorSystem[colorName] = {};
        }
        // Use the resolved value, not the reference
        colorSystem[colorName][shade] = token.value;
      } else if (token.type === 'spacing') {
        const spacingKey = token.path[token.path.length - 1];
        spacingScale[spacingKey] = token.value;
      } else if (token.type === 'boxShadow') {
        const shadowKey = token.path[token.path.length - 1];
        shadowScale[shadowKey] = token.value;
      }
    });

    return `// This file is generated by the build process
// DO NOT EDIT MANUALLY

export const colorSystem = ${JSON.stringify(colorSystem, null, 2)} as const;

export const spacingScale = ${JSON.stringify(spacingScale, null, 2)} as const;

export const shadowScale = ${JSON.stringify(shadowScale, null, 2)} as const;

export const flatTokens = {
  // Colors
  ...Object.entries(colorSystem).reduce((acc, [colorName, shades]) => {
    Object.entries(shades).forEach(([shade, value]) => {
      acc[\`color-\${colorName}-\${shade}\`] = value;
    });
    return acc;
  }, {} as Record<string, string>),
  
  // Spacing
  ...Object.entries(spacingScale).reduce((acc, [key, value]) => {
    acc[\`spacing-\${key}\`] = value;
    return acc;
  }, {} as Record<string, string>),
  
  // Shadows
  ...Object.entries(shadowScale).reduce((acc, [key, value]) => {
    acc[\`shadow-\${key}\`] = value;
    return acc;
  }, {} as Record<string, string>)
};

export const tokens = {
  color: colorSystem,
  spacing: spacingScale,
  shadow: shadowScale
};
`;
  }
});

const sd = new StyleDictionary({
  source: ['src/**/*.json'],
  platforms: {
    typescript: {
      transformGroup: 'js', // This resolves token references
      buildPath: 'src/',
      files: [{
        destination: 'tokens.generated.ts',
        format: 'typescript/tokens'
      }]
    },
    css: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [{
        destination: 'tokens.css',
        format: 'css/variables',
        selector: ':root'
      }]
    },
    js: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [{
        destination: 'tokens.js',
        format: 'javascript/module'
      }]
    }
  }
});

// Build all platforms with error handling
try {
  await sd.buildAllPlatforms();
  console.log('✅ Tokens built successfully');
  console.log('✅ TypeScript tokens generated with resolved references');
} catch (error) {
  console.error('❌ Token build failed:', error.message);
  process.exit(1);
}