import { defineConfig } from "tsup";

export default defineConfig((options) => ({
  entryPoints: [
    "src/button.tsx",
    "src/badge.tsx",
    "src/card.tsx",
    "src/input.tsx",
    "src/label.tsx",
    "src/textarea.tsx",
    "src/checkbox.tsx",
    "src/switch.tsx",
    "src/select.tsx",
    "src/separator.tsx",
    "src/tabs.tsx",
    "src/dialog.tsx",
    "src/dropdown-menu.tsx",
    "src/sheet.tsx",
    "src/alert.tsx",
    "src/avatar.tsx",
    "src/tooltip.tsx",
    "src/progress.tsx",
    "src/skeleton.tsx",
    "src/accordion.tsx",
    "src/breadcrumb.tsx",
    "src/radio-group.tsx",
    "src/alert-dialog.tsx",
    "src/hover-card.tsx",
    "src/popover.tsx",
    "src/context-menu.tsx",
    "src/command.tsx",
    "src/toggle.tsx",
    "src/toggle-group.tsx",
    "src/collapsible.tsx",
    "src/scroll-area.tsx",
    "src/slider.tsx",
    "src/pagination.tsx",
    "src/menubar.tsx",
    "src/navigation-menu.tsx",
    "src/table.tsx",
    "src/aspect-ratio.tsx",
    "src/resizable.tsx",
    "src/form.tsx",
    "src/toast.tsx",
    "src/calendar.tsx",
    "src/carousel.tsx",
  ],
  format: ["cjs", "esm"],
  dts: true,
  external: ["react"],
  outExtension({ format }) {
    return {
      js: format === "cjs" ? ".js" : ".mjs",
    };
  },
  ...options,
}));
